/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_homemods_relay_pi_bluetooth_BluetoothClientSocketNativeImpl */

#ifndef _Included_com_homemods_relay_pi_bluetooth_BluetoothClientSocketNativeImpl
#define _Included_com_homemods_relay_pi_bluetooth_BluetoothClientSocketNativeImpl
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_homemods_relay_pi_bluetooth_BluetoothClientSocketNativeImpl
 * Method:    connectN
 * Signature: (ILjava/lang/String;S)I
 */
JNIEXPORT jint JNICALL Java_com_homemods_relay_pi_bluetooth_BluetoothClientSocketNativeImpl_connectN
  (JNIEnv *, jobject, jint, jstring, jshort);

#ifdef __cplusplus
}
#endif
#endif
