/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_homemods_bluetooth_BluetoothServerSocketNativeImpl */

#ifndef _Included_com_homemods_bluetooth_BluetoothServerSocketNativeImpl
#define _Included_com_homemods_bluetooth_BluetoothServerSocketNativeImpl
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_homemods_bluetooth_BluetoothServerSocketNativeImpl
 * Method:    listenN
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_homemods_bluetooth_BluetoothServerSocketNativeImpl_listenN
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_homemods_bluetooth_BluetoothServerSocketNativeImpl
 * Method:    acceptConnectionN
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_homemods_bluetooth_BluetoothServerSocketNativeImpl_acceptConnectionN
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_homemods_bluetooth_BluetoothServerSocketNativeImpl
 * Method:    closeN
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_homemods_bluetooth_BluetoothServerSocketNativeImpl_closeN
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
