/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_homemods_bluetooth_BluetoothServerNativeImpl */

#ifndef _Included_com_homemods_bluetooth_BluetoothServerNativeImpl
#define _Included_com_homemods_bluetooth_BluetoothServerNativeImpl
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_homemods_bluetooth_BluetoothServerNativeImpl
 * Method:    allocSocket
 * Signature: (S)I
 */
JNIEXPORT jint JNICALL Java_com_homemods_bluetooth_BluetoothServerNativeImpl_allocSocket
  (JNIEnv *, jobject, jshort);

#ifdef __cplusplus
}
#endif
#endif
