/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_homemods_relay_pi_bluetooth_BluetoothClientNativeImpl */

#ifndef _Included_com_homemods_relay_pi_bluetooth_BluetoothClientNativeImpl
#define _Included_com_homemods_relay_pi_bluetooth_BluetoothClientNativeImpl
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_homemods_relay_pi_bluetooth_BluetoothClientNativeImpl
 * Method:    allocSocket
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_homemods_relay_pi_bluetooth_BluetoothClientNativeImpl_allocSocket
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
