/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_homemods_relay_pi_bluetooth_BluetoothSocketNativeImpl */

#ifndef _Included_com_homemods_relay_pi_bluetooth_BluetoothSocketNativeImpl
#define _Included_com_homemods_relay_pi_bluetooth_BluetoothSocketNativeImpl
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_homemods_relay_pi_bluetooth_BluetoothSocketNativeImpl
 * Method:    readN
 * Signature: (I[BI)I
 */
JNIEXPORT jint JNICALL Java_com_homemods_relay_pi_bluetooth_BluetoothSocketNativeImpl_readN
  (JNIEnv *, jobject, jint, jbyteArray, jint);

/*
 * Class:     com_homemods_relay_pi_bluetooth_BluetoothSocketNativeImpl
 * Method:    writeN
 * Signature: (I[BI)I
 */
JNIEXPORT jint JNICALL Java_com_homemods_relay_pi_bluetooth_BluetoothSocketNativeImpl_writeN
  (JNIEnv *, jobject, jint, jbyteArray, jint);

/*
 * Class:     com_homemods_relay_pi_bluetooth_BluetoothSocketNativeImpl
 * Method:    closeN
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_homemods_relay_pi_bluetooth_BluetoothSocketNativeImpl_closeN
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
